name: Шаблон
description: описание шаблона
title: "[Ошибка]: "
labels: ["bug"]


body:
  - type: textarea
    id: Header
    attributes:
      label: Header
      description: "Заголовок"
      placeholder: "Заголовок"
    validations:
      required: true

  - type: textarea
    id: Discription
    attributes:
      label: Discription
      description: "Описание"
      placeholder: "Описание"
    validations:
      required: true

  - type: textarea
    id: Steps
    attributes:
      label: Steps
      description: "Шаги воспроизведения "
      placeholder: "Шаги воспроизведения"
    validations:
      required: true

  - type: textarea
    id: ExpectedResults
    attributes:
      label: ExpectedResults
      description: "Ожидаемый результат"
      placeholder: "Ожидаемый результат"
    validations:
      required: true

  - type: textarea
    id: ActualResults
    attributes:
      label: ActualResults
      description: "Фактический  результат"
      placeholder: "Фактический  результат"
    validations:
      required: true

<p align="center"><img src="IMG_20260319_134151_339.jpg" alt="Typing SVG" /></a></p>
