name: Шаблон
description: описание шаблона
title: "[Ошибка]: "
labels: ["bug"]


body:
  - type: textarea
    id: Header
    attributes:
      label: Header
      description: "Заголовок"
      placeholder: "Заголовок"
    validations:
      required: true

  - type: textarea
    id: Discription
    attributes:
      label: Discription
      description: "Описание"
      placeholder: "Описание"
    validations:
      required: true

